import 'dart:math';

final List<String> healthTips = [
  "Stay hydrated; drink plenty of water throughout the day.",
  "Monitor your blood sugar levels regularly.",
  "Maintain a balanced diet rich in vegetables and whole grains.",
  "Choose high-fiber foods to help control blood sugar.",
  "Limit sugary drinks and snacks.",
  "Opt for whole fruits instead of fruit juices.",
  "Incorporate healthy fats like avocados and nuts into your diet.",
  "Eat smaller, more frequent meals to stabilize blood sugar.",
  "Practice portion control to avoid overeating.",
  "Choose lean protein sources like chicken, fish, and legumes.",
  "Avoid trans fats found in processed foods.",
  "Limit your intake of refined carbohydrates.",
  "Incorporate physical activity into your daily routine.",
  "Aim for at least 150 minutes of moderate exercise each week.",
  "Engage in strength training exercises at least twice a week.",
  "Prioritize sleep; aim for 7-9 hours of quality sleep.",
  "Manage stress through meditation or deep breathing exercises.",
  "Limit alcohol consumption and choose low-sugar options.",
  "Keep healthy snacks on hand to avoid temptation.",
  "Read nutrition labels carefully to understand carb content.",
  "Plan your meals in advance to stay on track.",
  "Keep a food diary to track your eating habits.",
  "Use herbs and spices for flavor instead of salt or sugar.",
  "Choose low-fat dairy options.",
  "Avoid skipping meals to prevent blood sugar spikes.",
  "Consult a dietitian for personalized meal planning.",
  "Stay consistent with your meal timing each day.",
  "Choose whole grain options over white bread or pasta.",
  "Incorporate beans and lentils into your meals.",
  "Avoid fried foods; opt for baking or grilling instead.",
  "Drink green tea for its potential health benefits.",
  "Practice mindful eating to better recognize hunger cues.",
  "Avoid eating late at night to aid digestion and blood sugar control.",
  "Monitor your blood pressure and cholesterol levels regularly.",
  "Stay informed about diabetes management strategies.",
  "Learn to recognize signs of high and low blood sugar.",
  "Use a continuous glucose monitor (CGM) if recommended by your doctor.",
  "Stay engaged with your healthcare team for regular check-ups.",
  "Keep your diabetes management tools (e.g., glucose meter) handy.",
  "Join a support group for emotional encouragement.",
  "Share your diabetes management goals with friends and family.",
  "Educate yourself about carbohydrate counting.",
  "Choose lower glycemic index foods when possible.",
  "Incorporate omega-3 fatty acids through sources like fish or flaxseeds.",
  "Avoid smoking and seek help to quit if necessary.",
  "Consider a walking group for motivation and social interaction.",
  "Take breaks during long periods of sitting to stay active.",
  "Use smaller plates to help control portion sizes.",
  "Experiment with new healthy recipes to keep meals exciting.",
  "Learn about the impact of stress on blood sugar levels.",
  "Keep healthy, diabetic-friendly snacks in your bag.",
  "Use food apps to track your carb intake and exercise.",
  "Experiment with plant-based meals to increase fiber intake.",
  "Stay away from high-sugar desserts; opt for fruit instead.",
  "Participate in diabetes education programs.",
  "Avoid using food as a reward or punishment.",
  "Stay connected with others who have diabetes for tips and support.",
  "Prioritize self-care and mental health.",
  "Be cautious with herbal supplements; consult your doctor first.",
  "Consider meal prepping to make healthy choices easier.",
  "Use healthy cooking methods, such as steaming or roasting.",
  "Reduce sodium intake to help manage blood pressure.",
  "Incorporate dark chocolate in moderation for its antioxidant benefits.",
  "Stay active by choosing walking meetings or taking the stairs.",
  "Use mindfulness techniques to avoid emotional eating.",
  "Limit high-fat meats and opt for fish or poultry instead.",
  "Pay attention to food cravings and find healthier substitutes.",
  "Consult your doctor about appropriate exercise levels.",
  "Limit fast food and choose healthier alternatives.",
  "Explore new fruits and vegetables to diversify your diet.",
  "Track your physical activity using a fitness app or wearable device.",
  "Limit processed snacks and choose whole food options.",
  "Engage in activities that bring you joy to reduce stress.",
  "Educate yourself about diabetes complications and prevention.",
  "Stay informed about new research and treatment options.",
  "Celebrate small victories in your diabetes management journey.",
  "Use visualization techniques to stay focused on your goals.",
  "Limit high-calorie coffee drinks; opt for black coffee or herbal tea.",
  "Share your struggles and successes with a trusted friend.",
  "Focus on creating a balanced plate at every meal.",
  "Consider yoga or tai chi for relaxation and flexibility.",
  "Stay consistent with your medication as prescribed.",
  "Keep healthy frozen meals on hand for busy days.",
  "Use olive oil or avocado oil for cooking instead of butter.",
  "Avoid eating straight from the package to control portions.",
  "Be patient with yourself; diabetes management is a journey.",
  "Engage in outdoor activities to enjoy fresh air and exercise.",
  "Educate yourself about the impact of various foods on blood sugar.",
  "Create a positive environment to encourage healthy habits.",
  "Find a workout buddy to stay motivated.",
  "Explore local farmer's markets for fresh produce.",
  "Try new cooking techniques to make healthy meals enjoyable.",
  "Limit the use of condiments high in sugar.",
  "Pay attention to hunger and fullness cues to prevent overeating.",
  "Stay committed to your health goals, even during setbacks.",
  "Seek advice from healthcare professionals about travel and diabetes.",
  "Make healthy lifestyle changes a family affair.",
  "Utilize online resources and apps for diabetes management.",
  "Keep a positive attitude and focus on your strengths.",
  "Remember that managing diabetes is a lifelong commitment; take it one day at a time."
];

String getRandomTip() {
  final random = Random();
  return healthTips[random.nextInt(healthTips.length)];
}
